#!/bin/bash

PID_FILE="/var/run/my_process.pid"
LOG_FILE="/tmp/my_process"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running"
    else
        # Start the process in the background
        nohup bash -c '
        while true; do
            echo "I am alive!" >> '"$LOG_FILE"'
            sleep 2
        done
        ' &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
    stop
    start
}

usage() {
    echo "Usage: $0 {start|stop|restart}"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        usage
        ;;
esac

